import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiGit,
  SiTailwindcss,
  SiFramer,
  SiSupabase,
  SiPostman,
  SiNodedotjs,
  SiExpress,
  SiMysql,
  SiSocketdotio,
  SiStyledcomponents,
  SiVite,
} from "react-icons/si";
import ReactQueryLogo from "./ReacyQueryLogo";

export { TbBrandReactNative } from "react-icons/tb";
export const iconMap = {
  HTML: SiHtml5,
  CSS: SiCss3,
  JavaScript: SiJavascript,
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  Redux: SiRedux,
  "Redux Toolkit": SiRedux,
  "React Query": ReactQueryLogo,
  Git: SiGit,
  Tailwind: SiTailwindcss,
  "Framer Motion": SiFramer,
  Supabase: SiSupabase,
  Postman: SiPostman,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  MySQL: SiMysql,
  "Socket.io": SiSocketdotio,
  StyledComponent: SiStyledcomponents,
  Vite: SiVite,
};

export const colorMap = {
  HTML: "text-[#E34F26]",
  CSS: "text-[#1572B6]",
  JavaScript: "text-[#F7DF1E]",
  "React.js": "text-[#61DAFB]",
  "Next.js": "text-[#000000] dark:text-white",
  Redux: "text-[#764ABC]",
  "Redux Toolkit": "text-[#764ABC]",
  "React Query": "",
  // "React Query": "text-[#FF4154]",
  Git: "text-[#F05032]",
  Tailwind: "text-[#06B6D4]",
  "Framer Motion": "text-[#0055FF]",
  Supabase: "text-[#3ECF8E]",
  Postman: "text-[#FF6C37]",
  "Node.js": "text-[#339933]",
  "Express.js": "text-[#000000] dark:text-white",
  MySQL: "text-[#4479A1]",
  "Socket.io": "text-[#010101] dark:text-white",
  StyledComponent: "",
  Vite: "",
};
