import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiGit,
  SiTailwindcss,
  SiFramer,
  SiSupabase,
  SiPostman,
  SiNodedotjs,
  SiExpress,
  SiMysql,
  SiSocketdotio,
  SiStyledcomponents,
} from "react-icons/si";
import { ReactQueryLogo, ViteIcon, StyledComponentsIcon } from "./Icons";

export { TbBrandReactNative } from "react-icons/tb";
export const iconMap = {
  HTML: SiHtml5,
  CSS: SiCss3,
  JavaScript: SiJavascript,
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  Redux: SiRedux,
  "Redux Toolkit": SiRedux,
  "React Query": ReactQueryLogo,
  Git: SiGit,
  Tailwind: SiTailwindcss,
  "Framer Motion": SiFramer,
  Supabase: SiSupabase,
  Postman: SiPostman,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  MySQL: SiMysql,
  "Socket.io": SiSocketdotio,
  StyledComponent: SiStyledcomponents,
  Vite: ViteIcon,
};

export const colorMap = {
  HTML: "text-[#E34F26]",
  CSS: "text-[#1572B6]",
  JavaScript: "text-[#F7DF1E]",
  "React.js": "text-[#61DAFB]",
  "Next.js": "text-[#000000] dark:text-white",
  Redux: "text-[#764ABC]",
  "Redux Toolkit": "text-[#764ABC]",
  "React Query": "",
  Git: "text-[#F05032]",
  Tailwind: "text-[#06B6D4]",
  "Framer Motion": "text-[#0055FF]",
  Supabase: "text-[#3ECF8E]",
  Postman: "text-[#FF6C37]",
  "Node.js": "text-[#339933]",
  "Express.js": "text-[#000000] dark:text-white",
  MySQL: "text-[#4479A1]",
  "Socket.io": "text-[#010101] dark:text-white",
  StyledComponent: "",
  Vite: "",
};
export const techLogos = {
  HTML: { svg: SiHtml5, color: "text-[#E34F26]" },
  CSS: { svg: SiCss3, color: "text-[#1572B6]" },
  JavaScript: { svg: SiJavascript, color: "text-[#F7DF1E]" },
  "React.js": { svg: SiReact, color: "text-[#61DAFB]" },
  "Next.js": { svg: SiNextdotjs, color: "text-[#000000] dark:text-white" },
  Redux: { svs: SiRedux, color: "text-[#764ABC]" },
  "Redux Toolkit": { svg: SiRedux, color: "text-[#764ABC]" },
  "React Query": { svg: ReactQueryLogo, color: "" },
  Git: { svg: SiGit, color: "text-[#F05032]" },
  Tailwind: { svg: SiTailwindcss, color: "text-[#06B6D4]" },
  "Framer Motion": { svg: SiFramer, color: "text-[#0055FF]" },
  Supabase: { svg: SiSupabase, color: "text-[#3ECF8E]" },
  Postman: { svg: SiPostman, color: "text-[#FF6C37]" },
  "Node.js": { svg: SiNodedotjs, color: "text-[#339933]" },
  "Express.js": { svg: SiExpress, color: "text-[#000000] dark:text-white" },
  MySQL: { svg: SiMysql, color: "text-[#4479A1]" },
  "Socket.io": { svg: SiSocketdotio, color: "text-[#010101] dark:text-white" },
  StyledComponent: { svg: SiStyledcomponents, color: "" },
  Vite: { svg: ViteIcon, color: "" },
};
